sandbox_mode = "workspace-write"
#model_reasoning_effort = "medium"
model_reasoning_summary = "none"
model_verbosity = "low"
project_doc_fallback_filenames = ["CLAUDE.md"]

[features]
web_search_request = true

[shell_environment_policy]
# inherit can be "all" (default), "core", or "none"
#inherit = "all"
# set to true to *skip* the filter for `"*KEY*"` and `"*TOKEN*"`
#ignore_default_excludes = false
# exclude patterns (case-insensitive globs)
#exclude = ["AWS_*", "AZURE_*"]
# force-set / override values
#set = { CI = "1" }
# if provided, *only* vars matching these patterns are kept
#include_only = ["PATH", "HOME"]

[history]
persistence = "none"

[tui]
notifications = false
animations = false